<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Flunt" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessControlSystem.Domain\AccessControlSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\UserContext\Create\Contracts\" />
    <Folder Include="Context\UserContext\Get\" />
    <Folder Include="Context\UserContext\GetMe\" />
    <Folder Include="Context\UserContext\Activate\" />
    <Folder Include="Context\UserContext\Deactivate\" />
    <Folder Include="Context\UserContext\UpdateMe\" />
    <Folder Include="Context\UserContext\Update\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
